Update ansible_bash
Latest working version integrated with K8s secrets

diff --git a/ansible/ansible_bash b/ansible/ansible_bash
--- a/ansible/ansible_bash
+++ b/ansible/ansible_bash
@@ -1,16 +1,149 @@
 #!/bin/bash
 
-if [ "$#" -ne 1 ]; then
-    echo "This script requires 1 parameter: Name of the cluster"
-    exit 1
+#Set the Opsgenie API KEY 
+api_key=$(kubectl get secret opsgenie-apikey -n monitoring -o jsonpath='{.data.apikey}'|base64 --d
+ecode)
+
+#Opsgenie API URLs
+create_alert_url="https://api.eu.opsgenie.com/v2/alerts"
+close_alert_url="https://api.eu.opsgenie.com/v2/alerts/"
+list_alerts_url="https://api.eu.opsgenie.com/v2/alerts"
+
+#Function to send an alert to Opsgenie
+send_opsgenie_alert() {
+message="$1"
+priority="$2"
+description="$3"
+
+headers=(
+    "Authorization: GenieKey $api_key"
+)
+
+headercontent=(
+    "Content-type: application/json"
+)
+
+payload=$(cat <<EOF
+{
+"message": "$message",
+"priority": "$priority",
+"description": "$description",
+"responders":[
+        {"name":"APP-ABN", "type":"team"}
+    ]
+}
+EOF
+)
+
+response=$(curl -s -X POST -H "$headers" -H "$headercontent" -d "$payload" "$create_alert_url")
+alert_id=$(jq -r '.requestId' <<<"$response")
+if [[ -n $alert_id ]]; then
+    echo "Alert sent to Opsgenie successfully!"
+else
+    echo "Failed to send alert to Opsgenie. RequestID: $(jq -r '.requestId' <<<"$response")"
+    echo "Response: $response"
+    return 1 
+fi
+}
+
+#Function to close an alert in Opsgenie
+close_opsgenie_alert() {
+alertId="$1"
+
+headers=(
+    "Authorization: GenieKey $api_key"
+)
+
+payload=$(cat <<EOF
+{
+    "user":"Monitoring Script",
+    "source":"automatic script TODO URL bitbucket",
+    "note":"Action executed via Alert API"
+}
+EOF
+)
+
+response=$(curl -s -X POST -H "${headers[@]}" -H "Content-Type: application/json" -d "$payload" "$
+close_alert_url/$alertId/close")
+
+if [[ -n $(jq -r '.requestId' <<<"$response") ]]; then
+    echo "Alert closed successfully!"
+else
+    echo "Failed to close alert. Status Code: "$response")"
+fi
+}
+
+#Function to get related alerts from Opsgenie
+get_related_alerts() {
+incident_message="$1"
+
+headers=(
+    "Authorization: GenieKey $api_key"
+)
+
+params=(
+    "query=message:%20"$incident_message"%20AND%20status:%20open&limit=10&sort=createdAt&order=des
+c"
+)
+
+response=$(curl -s -X GET -H "${headers[@]}" "$list_alerts_url?${params[@]}")
+
+data=$(jq -r '.data[].id' <<<"$response")
+ 
+if [[ -n $data ]]; then
+  echo "$data"
+else
+  echo ""
+  return -1
+fi
+}
+
+#Function to print the script usage
+print_usage() {
+  echo "Usage: $0 <message> <priority P1-P4 or close>" 
+  echo "Parameters:"
+  echo " <message> The incident message to check"
+  echo " <priority> Priority of the alert (P1, P2, P3, P4) or (close) to close the alert"
+  echo " [description] Optional: Description of the alert to give details for the alert"
+  exit 1
+}
+
+# Main starts here
+# Validate and retrieve command-line arguments
+if [[ $# < 2 || $# > 3 ]]; then
+  print_usage
 fi
 
-cluster=$1
-jump_node=ccp04e	
+alert_message="$1"
+priority="$2"
+alert_description="$3"
 
-echo get the list of nodes in the cluster
+# Validate priority parameter
+valid_priorities=("P1" "P2" "P3" "P4" "close")
+if [[ ! " ${valid_priorities[@]} " =~ " $priority " ]]; then
+  echo "Invalid value for <priority>. Use one of: ${valid_priorities[@]}"
+  print_usage
+fi
 
-ssh $jump_node "kubectx $cluster > /dev/null && kubectl get nodes -o name|cut -f2 -d'/'" > $cluster.ansible_hosts.txt
+# Check if there are related alerts
+related_alerts=$(get_related_alerts "$alert_message")
 
-ansible-playbook \
---inventory  $cluster.ansible_hosts.txt --ask-pass --ask-become-pass fstab.yaml
+if [[ $priority == "close" ]]; then
+# Here we check if there are related alerts and if we close them
+  if [ ${#related_alerts[@]} -ne 0 ]; then
+  # Close related alerts
+  while IFS= read -r alert; do
+    close_opsgenie_alert "$alert"
+  done <<<"$related_alerts"
+    echo "Resolved incident. Closed related alerts."
+  else
+    echo "Resolved incident. No related alerts to close."
+  fi
+else
+ if [[ -n $related_alerts ]]; then
+   echo "Incident still exists. Related alerts already present."
+ else
+  # Send a new alert
+    send_opsgenie_alert "$alert_message" "$priority" "$alert_description"
+  fi
+fi
